imports:
    - { resource: buildings.yml }

services:
    citadels_core.character_card_service:
        class: Citadels\CoreBundle\DependencyInjection\Service\CharacterCardService

    citadels_core.building_card_service:
        class: Citadels\CoreBundle\DependencyInjection\Service\BuildingCardService
        arguments: ['%citadels_core.building_cards%']

    citadels_core.player_service:
        class: Citadels\CoreBundle\DependencyInjection\Service\PlayerService
        arguments: [@citadels_core.character_card_service]

    citadels_core.character_card_mapper:
        class: Citadels\CoreBundle\Models\ViewModel\Mapper\CharacterCardMapper
        arguments: [@citadels_core.character_card_service]

    citadels_core.player_mapper:
        class: Citadels\CoreBundle\Models\ViewModel\Mapper\PlayerMapper
        arguments: [@citadels_core.player_service, @citadels_core.character_card_mapper]
